version: '3'

services:
  webgoat7:
    image: webgoat/webgoat-7.1
    container_name: "webgoat7"
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:8080/WebGoat/login.mvc"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "127.0.0.1:8087:8080"
  webgoat8:
    image: webgoat/webgoat-8.0
    container_name: "webgoat8"
    user: webgoat
    volumes:
      - ./wget.sh:/tmp/wget.sh
    healthcheck:
      test: ["CMD", "bash", "/tmp/wget.sh", "http://127.0.0.1:8080/WebGoat/login"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
      - spring.datasource.url=jdbc:postgresql://webgoat_db:5432/webgoat?user=webgoat&password=webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
      - webgoat.server.directory=/home/webgoat/.webgoat/
      - webgoat.user.directory=/home/webgoat/.webgoat/
    ports:
      - "127.0.0.1:8080:8080"
  webwolf:
    image: webgoat/webwolf
    container_name: "webwolf"
    environment:
      - spring.datasource.url=jdbc:postgresql://webgoat_db:5432/webgoat?user=webgoat&password=webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
    ports:
      - "127.0.0.1:9090:9090"
  webgoat_db:
    container_name: "webgoat8-db"
    image: postgres:9.4
# Uncomment to store the state of the database on the host.
#    volumes:
#      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=webgoat
      - POSTGRES_USER=webgoat
      - POSTGRES_DB=webgoat
